### PR TITLE
Sprint 2 - refactorization

### PR DESCRIPTION
**Pull request by yo1995**
More details to add here.

Please refer to #10 for a general outline of the goals of this sprint.

### CODE REVIEW

**Comment by yo1995** [comment]
The linter is in place to stop me from bad styling... 😅  Nice job!

**Comment by yo1995** [comment]
@profRic This PR is good to demo now, though it requires additional setup to build. We may discuss before meeting with clients.

**Comment by yo1995** [comment]
A brief line count of Sprint 2

```sh
find . "(" -name "*.swift" ")" -print0 | xargs -0 wc -l
```

      35 ./Models/Game/Game.swift
      21 ./Models/Game/GameGroup.swift
      14 ./Models/Game/PlayersQueue.swift
      78 ./Models/Game/GameStore.swift
      20 ./Models/Game/GameOfGroup.swift
     126 ./Models/Question/QuestionStepsModel.swift
      30 ./Models/Question/QuestionType.swift
      47 ./Models/Question/Questionnaire.swift
     128 ./Models/Chatroom/Message.swift
      50 ./Models/Chatroom/Chatroom.swift
      18 ./Models/Chatroom/ChatUser.swift
      16 ./Models/Genders.swift
      13 ./Models/LocalErrors.swift
      66 ./Models/Profiles.swift
      19 ./Models/Player.swift
      24 ./Models/Onboarding/OnboardingStateManager.swift
     135 ./Models/Onboarding/OnboardingSteps.swift
      28 ./Extensions/String+sha256.swift
      19 ./Extensions/UIColor.swift
      23 ./Extensions/UICollectionView.swift
      29 ./Extensions/UIImage.swift
      36 ./Extensions/UIViewController.swift
     358 ./Supporting Files/PopulateGames.swift
      43 ./AppDelegate.swift
     395 ./Controllers/Home/ChatViewController.swift
     134 ./Controllers/Home/HomeCollectionViewController.swift
     219 ./Controllers/Home/MatchingViewController.swift
     103 ./Controllers/Home/GameViewController.swift
      81 ./Controllers/RootTabBarController.swift
      27 ./Controllers/Custom steps/ResourceWebStep.swift
      64 ./Controllers/Custom steps/ResourceWebStepViewController.swift
     106 ./Controllers/OnboardingViewController.swift
      45 ./Controllers/Profile/DemographicsViewController.swift
      62 ./Controllers/Profile/ProfileViewController.swift
      16 ./Controllers/RoadmapViewController.swift
      22 ./Views/ProfileHeaderView.swift
      22 ./Views/GameCollectionCell.swift
      11 ./Protocols/DatabaseRepresentation.swift
      56 ./SceneDelegate.swift
    2739 total

**Comment by profRic** [comment]
Let me know which branch to download and test.  I have time this weekend to catch up on this.

**Comment by yo1995** [comment]
> Let me know which branch to download and test. I have time this weekend to catch up on this.

Sounds good. I'll merge this PR tonight and setup a temporary branch that use Carthage #35 to make it easy for you to set up the build environment. I'll let you know in Slack later.

**Comment by yo1995** [comment]
Refer to #39 for testing details.

**Pull request merged**
